#!/bin/sh

bspc monitor primary -d 1 2 3 4 5 6 7

bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr

bspc config borderless_monocle false
bspc config single_monocle false
bspc config gapless_monocle false

bspc config border_width 0
bspc config pointer_motion_interval 5

bspc config split_ratio 0.52
