#!/usr/bin/env bash

CHOICE=$(echo -e "Suspend\nReboot\nShutdown" | rofi -dmenu -p "Power Menu" -theme-str 'window {width: 20%;}')

case "$CHOICE" in
  Suspend)
    systemctl suspend
    ;;
  Reboot)
    systemctl reboot
    ;;
  Shutdown)
    systemctl poweroff
    ;;
  *)
    ;;
esac
